### ISSUE TITLE
Create Python Unit Tests

### ISSUE THREAD

**Issue by WilliamIX** [WilliamIX/BioCRNPyler#14]
Many of the current "tests" could then be moved to an example folder.

**Comment by ayush9pandey** [comment]
Agree.

**Comment by zoltuz** [comment]
I've moved the current tests to the example folder and created some unittest. Please have  a look in #23

**Comment by zoltuz** [comment]
PR #41 has the implementation for the unit tests. Of course more tests are needed, but the basics are covered. I'm closing this issue now.
