### ISSUE TITLE
Example Jupyter Notebook(s)

### ISSUE THREAD

**Issue by WilliamIX** [WilliamIX/BioCRNPyler#28]

**Comment by WilliamIX** [comment]
I have created one example workbook for developers explaining how to make custom Mixtures, Components, and Mechanisms.

I think we need 2 more example workbooks but welcome your comments:
1) A basic getting started workbook showing the easy to use functionality. This requires the high level wrappers (Tube-speak so to speak) to be written.
2) A more advanced feature workbook, showing how custom mechanisms can be used (I already have many of these made). I would like to use tube-speak for these as well, so I will port them over as soon as that part is finished. I would also like to add something about parameter loading to this notebook - so that example will require that we figure out how parameter loading works.

Am I missing anything?

**Comment by zoltuz** [comment]
#51 added this feature
