### ISSUE TITLE
ModuleNotFoundError (s) when running tests

### ISSUE THREAD

**Issue by ayush9pandey** [WilliamIX/BioCRNPyler#3]
Needs __init__.py to create a Python module which can be imported in other files. 

In the current version of the code, running any file in the tests/ directory throws an error `ModuleNotFoundError` - No module named - `txtl`, `chemical_reaction_network` etc.

Also, `regulated_promoter_activation_and_repression.py` imports `CRN_simulator` (which also throws ModuleNotFoundError, but also I couldn't find any file named `CRN_simulator` in the directory.

**Comment by ayush9pandey** [comment]
Moving the code `repr_for_crn_and_component_and_write_to_sbml.py` out of tests folder into the main directory gets rid of the `ModuleNotFoundError` (but throws another error "write_sbml_file" is not an attribute), so, as expected -- need to make a module using `__init__.py` and then import classes out of this module (if this change is made, then the import statements in all of the classes and tests file would need an update too)

Probably, can create a `biocrnpyler` package name, with all the classes inside, which would enable statements like - 
``` 
from biocrnpyler import * 
```
(would probably be helpful to look at `txtlsim-python` repository and copy the directory and import structure from over there?)

**Comment by WilliamIX** [comment]
I added an __init__.py and setup.py as you suggested, let me know if they work!

**Comment by murrayrm** [comment]
A couple of thoughts on this:

* The current directory structure is non-standard for a Python package.  What things would normally look is this
```
biocrnpyler/          # repository main directory
    LICENSE           # LICENSE information for the package
    README            # README file for the package
    biocrnpyler/      # The actual package (this is what gets installed)
        __init__.py   # Package initialization (called when you do import biocrnplyler
       <module>.py    # The modules that make up the package
    doc/              # Documentation (eg, sphinx)
    examples/         # Examples
    tests/            # Unit tests
    setup.py          # Setup script
```

* When running a script from the command line, the Python interpreter add the directory where the script resides to the current path, but does not add the directory that Python was called from.  So if you want to run something in the examples directory using the current source code, you might call the following from the repository main directory:
```
PYTHONPATH=. python examples/example_file.py
```

**Comment by ayush9pandey** [comment]
Currently, the code is working but only when the file is inside the package (which should not be the case). 

So, as Richard suggested, we need to have the standard directory structure and also fix the PYTHONPATH to run a code from another folder. 

I will attempt to fix this by structuring the directory, fixing the import relationships in the classes, and then will also setup the MANIFEST and setup.py files to install the package.

**Comment by WilliamIX** [comment]
Thanks Ayush! Glad the code is working (ish) now. Also, are you working under the master branch or your own development branch? just want to make sure we keep track and everything merges appropriately.

**Comment by ayush9pandey** [comment]
I am working on my fork of your repository and am tracking it with the changes of the upstream/master (your master branch), will create a pull request once I make changes that work and then it should merge properly.

⁣Sent from BlueMail ​

**Comment by WilliamIX** [comment]
I believe we can close this now thanks to Ayush's work.
