### ISSUE TITLE
How are parameters loaded from a file?

### ISSUE THREAD

**Issue by WilliamIX** [WilliamIX/BioCRNPyler#33]

**Comment by WilliamIX** [comment]
Does anyone have a vision for how to best deal with this? I will then happily implement!

**Comment by WilliamIX** [comment]
Length and initial concentration will also be automatically pulled from a file for DNA assemblies and default components in a Mixture.

**Comment by WilliamIX** [comment]
@ayush9pandey The basic parameter loading function has been committed to master. Not thoroughly tested yet though (but all examples still work).

**Comment by WilliamIX** [comment]
I've been working with this function (fixed a few small errors) and creating an example jupyter notebook in the WPDev Branch. Will upload to master in the next few days

**Comment by zoltuz** [comment]
It looks good for now, I've added unit tests around it to ensure the correct behavior. Also, I've added some fool proofing asserts in #41. Closing this, as it has been solved for now.
