### ISSUE TITLE
Validate the SBML models generated.

### ISSUE THREAD

**Issue by ayush9pandey** [WilliamIX/BioCRNPyler#34]

**Comment by WilliamIX** [comment]
I will simulate via SBML and simulate directly with bioscrape. Make sure both work.

Ayush will add code to check the integrity of the SBML file before we write it.

**Comment by ayush9pandey** [comment]
SBML models that have local parameters having multiple parameters with the same name don't simulate with bioscrape right now. 

Other than that, I have implemented SBML error checking in `chemical_reaction_network.py` and also in `crnlab.py` in my latest commit.  On finding an error - a warning will be printed that SBML document might have errors. 

There's also a new function that users can call at the end to validate the model generated - `txtl.validate_sbml_generated()`

**Comment by WilliamIX** [comment]
@ayush9pandey  can you give me an example of something that doesn't work with bioscrape? I will then try to find the problem and fix it.

I like the idea of validating an sbml model - but this should be a bioscrape feature, not a BioCRNpyler feature. BioCRNpyler has no way of loading SBML I believe (correct me if I'm wrong).

**Comment by ayush9pandey** [comment]
The SBML model [here](https://github.com/ayush9pandey/BioCRNPyler/blob/master/examples/GFP.xml) shouldn't work with bioscrape. 

We are generating new SBML models from bioCRNpyler (that could potentially be used with any simulator that the user wants), so need to be sure that the SBML file generated is free of errors. 

We could implement similar error checking with bioscrape when loading an SBML model. This is more or less already there with warnings that are printed out if there are things in an SBML model that bioscrape doesn't recognize, but we could add more checks for sure (but that should be an issue on that repository :)

**Comment by ayush9pandey** [comment]
Addressed in #51
