### ISSUE TITLE
Delete all temporary files/folders such as (biocrnpyler.egg, build, dist etc.) from the repo

### ISSUE THREAD

**Issue by ayush9pandey** [WilliamIX/BioCRNPyler#36]
Not a priority for sure but we should look into it in the future so that these temporary files and folders are automatically deleted each time after the python setup is run.

Until the time it is not fixed I try to push the code each time by manually deleting these temp files first.

**Comment by zoltuz** [comment]
I agree, I'm having the same issue. Could you update the gitignore file in the next push, so these temp files won't come back?

**Comment by ayush9pandey** [comment]
I have deleted the temp files and modified the gitignore, these changes are also available in PR #38
