### ISSUE TITLE
add_components should have load parameter option as a dictionary?

### ISSUE THREAD

**Issue by ayush9pandey** [WilliamIX/BioCRNPyler#37]
Not sure if I am got this right but according to me in our last discussion, we decided to have options to load extra parameters to a mixture (if the user desires to overwrite or load extra parameters later on). So, does this feature go in as an option to add_component ?

**Comment by WilliamIX** [comment]
Please look at the Parameter Jupyter Notebook examples for a full overview of how all this stuff works.

**Comment by ayush9pandey** [comment]
Closing this issue, as it was fixed with the new Parameter class.
