### ISSUE TITLE
"complex" is a built in python function - we should not overwrite it

### ISSUE THREAD

**Issue by WilliamIX** [WilliamIX/BioCRNPyler#39]
I suggest we change this to "species_complex" or something similar.

**Comment by ayush9pandey** [comment]
I agree. 

I think this change needs to be made in `component.py` and then reflected everywhere else it's referred.

**Comment by WilliamIX** [comment]
yes, chemical_reaction_network.complex has been changes to chemical_reaction_network.species_complex. Is there also a complex in component?

**Comment by ayush9pandey** [comment]
There's a class called Complex in component.py, not sure if we want to change that as well.

**Comment by WilliamIX** [comment]
Lets call it ComponentComplex...I bet I use it in the dCas9 example, but probably nowhere else.

**Comment by zoltuz** [comment]
I guess, this has been resolved. I'm closing it.
