### ISSUE TITLE
"buffer" is a built-in python function - we should not overwrite it

### ISSUE THREAD

**Issue by sclamons** [WilliamIX/BioCRNPyler#40]
There are some variables named "buffer". We should change these to "reaction_buffer" or something similar.

**Comment by ayush9pandey** [comment]
I have commented it out in my latest commit, so should be fine with my next PR. This is for the CRNLab class only, I am not 100% sure if there is a buffer function defined elsewhere too. 

@WilliamIX  : Did you create any function named buffer? If not, we should be good to go with my PR.

**Comment by WilliamIX** [comment]
I do not believe I created anything called buffer.

**Comment by zoltuz** [comment]
I did a global search and renamed buffer to txtl_buffer in the CRNLab, no other instance was found. 
I'm closing this now.
