### ISSUE TITLE
repo clean up

### ISSUE THREAD

**Issue by zoltuz** [WilliamIX/BioCRNPyler#42]
Hi all,
There're some files that are cluttering up the repo and should be removed. I've already set up the .gitignore in #41 , but they needed to be  physically removed, my suggestions:

git rm -r .idea
git rm -r Presentations and Documentation
git rm -r examples/.ipynb_checkpoints/
git commit -m'repo clean up'

Let me know what you think!

Zoltan

**Comment by ayush9pandey** [comment]
Agree with your suggestions.

**Comment by zoltuz** [comment]
also we can add one more delete to the list:
git rm biocrnpyler/chemical_reaction_network.py.orig

**Comment by ayush9pandey** [comment]
I can still see some of these files, was this commit not included in your PR?

**Comment by zoltuz** [comment]
Sorry, I forgot to communicate my plan: first, we merge my latest PR (done), then we merge yours Ayush, once everything is merged, I checkout William's repo and directly delete the files there.  Would that work for you? (I'd prefer deleting things in one place and then updating all the forks).

**Comment by ayush9pandey** [comment]
That works for me. I had deleted that in my fork, but I can get it back.

**Comment by zoltuz** [comment]
cleaned up, good to go!
