### ISSUE TITLE
adding Species as a component

### ISSUE THREAD

**Issue by zoltuz** [WilliamIX/BioCRNPyler#45]
Hi, 

When a Mixture object is initialized, then a Species object can be added to the components list, but with add_components it is not possible 

```
from biocrnpyler import Mixture
from biocrnpyler import Species
species = Species('test_species')
mixture = Mixture(component=[species])
```

But the add_components doesn't support Species object(s) (Species is inherited from Object, not from Component)
```
 def add_components(self, components):
        if isinstance(components, Component):
            components = [components]

        for component in components:
            if isinstance(component, Component):
                self.components.append(component)
                component.update_mechanisms(mixture_mechanisms=self.mechanisms)
                component.update_parameters(mixture_parameters=self.parameters)
                if self.parameter_warnings is not None:
                    component.set_parameter_warnings(self.parameter_warnings)
            else:
                warn("Non-component added to mixture "+self.name,
                     RuntimeWarning)
```

Is this intended or just a bug? Thanks for looking into it!

Zoltan

**Comment by WilliamIX** [comment]
I'm not sure - I think I didn't think the design through thoroughly. I think we should be consistent - so maybe having the Mixture(species = species, components = components) as the constructor? Alternatively [for ease] I don't mind overloading components to allow species to be added directly, in which case add component should also take Species.

**Comment by zoltuz** [comment]
I've added an implementation to solve this question in  5120a36, It will be merged with the next PR.
