### ISSUE TITLE
In Parameters ipython notebook :  ValueError: No Parameters can be found for rna_degradation_mm

### ISSUE THREAD

**Issue by ayush9pandey** [WilliamIX/BioCRNPyler#49]
This is the error that I am getting on running the Parameters notebook - 

ValueError: No Parameters can be found that match the (mechanism, param_id, param_name)=(rna_degredation_mm, None, ku)

This parameter is in the .tsv file but for some reason is not read. In case I remember correctly, this notebook was working earlier and so it must be a minor bug from some of the later commits. 

I will try to find out the bug and fix it in my PR, it would be helpful if you have a suggestion on how to fix this.

**Comment by zoltuz** [comment]
I guess that was me, sorry about that. I've tracked down where it is generated, just need to find a fix. Stay tuned!

**Comment by zoltuz** [comment]
#50 fixes it! Also it fixes couple of other issues (referenced in the commit message)

**Comment by ayush9pandey** [comment]
Yes, it is fixed in #50
