### ISSUE TITLE
Use `SetIdFromNames` before assigning SBML IDs for components or ensure uniqueness

### ISSUE THREAD

**Issue by ayush9pandey** [WilliamIX/BioCRNPyler#6]
This is an issue from `txtlsim-python` that has carried over. SBML model requires unique ids be given to all components. I checked the SBML model generated in the current code and passed it through SBML validator which returned the error - 

> This document is not valid SBML!
> 2 Errors
> Error Line 62 Column 35: (SBML Validation Rule #10301) The value of the 'id' field on every instance of 
> the following type of object in a model must be unique .............

Two ways we can fix this - 
1. Ensure manually that we are not giving duplicate ids to each and every component in the model.
2. Use the `SetIdFromNames.py` class provided by libsbml-Python always before setting an id (this class ensures SBML SId rules are followed and also makes sure to create an id which is not already used in the model).

**Comment by ayush9pandey** [comment]
I have fixed this issue using Option 2, it will be reflected in my pull request later.

**Comment by murrayrm** [comment]
For the future: best to leave the issue open until the pull request is merged (since it might not be accepted and then the issue could get lost).

**Comment by ayush9pandey** [comment]
Yes, didn't think about that, reopened it.

**Comment by WilliamIX** [comment]
Merged and closed.
